### ISSUE TITLE
feather command does not exist

### ISSUE THREAD

**Issue by Foritus** [crzysdrs/DailyVictimArchive#2]
Hello :) In Build.hs (line 127) there's a call out to a "feather" command line tool, but that command doesn't seem to exist. Is this a wrapper around some imagemagick functions?

**Comment by crzysdrs** [comment]
Yes. The feather tool can be found at:
http://www.fmwconcepts.com/imagemagick/feather/

**Comment by Foritus** [comment]
Aha, thank you.
